export const COUNTRY_CODE_MAP: Record<string, string> = {
  Portugal: "PT",
  Espanha: "ES",
  Spain: "ES",
  França: "FR",
  France: "FR",
  Alemanha: "DE",
  Germany: "DE",
  "Reino Unido": "GB",
  "United Kingdom": "GB",
  UK: "GB",
  "Itália": "IT",
  Italy: "IT",
  Holanda: "NL",
  Netherlands: "NL",
  Bélgica: "BE",
  Belgium: "BE",
  Suíça: "CH",
  Switzerland: "CH",
  Áustria: "AT",
  Austria: "AT",
  Suécia: "SE",
  Sweden: "SE",
  Noruega: "NO",
  Norway: "NO",
  Dinamarca: "DK",
  Denmark: "DK",
  Finlândia: "FI",
  Finland: "FI",
  Polónia: "PL",
  Poland: "PL",
  Ucrânia: "UA",
  Ukraine: "UA",
  Turquia: "TR",
  Turkey: "TR",
  Rússia: "RU",
  Russia: "RU",
  "Estados Unidos": "US",
  "United States": "US",
  USA: "US",
  Canadá: "CA",
  Canada: "CA",
  México: "MX",
  Mexico: "MX",
  Brasil: "BR",
  Brazil: "BR",
  Argentina: "AR",
  Chile: "CL",
  Colômbia: "CO",
  Colombia: "CO",
  Peru: "PE",
  Venezuela: "VE",
  "África do Sul": "ZA",
  "South Africa": "ZA",
  Egipto: "EG",
  Egypt: "EG",
  Nigéria: "NG",
  Nigeria: "NG",
  Quénia: "KE",
  Kenya: "KE",
  Marrocos: "MA",
  Morocco: "MA",
  China: "CN",
  Índia: "IN",
  India: "IN",
  Japão: "JP",
  Japan: "JP",
  "Coreia do Sul": "KR",
  "South Korea": "KR",
  Indonésia: "ID",
  Indonesia: "ID",
  Tailândia: "TH",
  Thailand: "TH",
  Vietname: "VN",
  Vietnam: "VN",
  Malásia: "MY",
  Malaysia: "MY",
  Filipinas: "PH",
  Philippines: "PH",
  Singapura: "SG",
  Singapore: "SG",
  Austrália: "AU",
  Australia: "AU",
  "Nova Zelândia": "NZ",
  "New Zealand": "NZ",
  Emirados: "AE",
  "United Arab Emirates": "AE",
  "Arábia Saudita": "SA",
  "Saudi Arabia": "SA",
  Israel: "IL",
  Grécia: "GR",
  Greece: "GR",
  Roménia: "RO",
  Romania: "RO",
  "República Checa": "CZ",
  "Czech Republic": "CZ",
  Hungria: "HU",
  Hungary: "HU",
};

export function getCountryCode(countryName: string): string {
  return COUNTRY_CODE_MAP[countryName] || countryName.slice(0, 2).toUpperCase();
}
