import { Appearance } from "./types";

export interface TemplatePreset {
  id: string;
  name: string;
  theme: "dark" | "light";
  appearance: Partial<Appearance> & { backgroundColor: string };
}

export const PREMIUM_TEMPLATES: TemplatePreset[] = [
  {
    id: "liquid-glass",
    name: "Liquid Glass",
    theme: "dark",
    appearance: {
      backgroundColor: "#0a0a0a",
      cardColor: "rgba(255,255,255,0.03)",
      textColor: "#fafafa",
      accentColor: "#ffffff",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "glass",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 35,
      glassBlur: 25,
      glassStrength: 50,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    theme: "dark",
    appearance: {
      backgroundColor: "#09090b",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#f4f4f5",
      accentColor: "#a1a1aa",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "solid",
      buttonRadius: 14,
      buttonWidth: "full",
      glassOpacity: 30,
      glassBlur: 20,
      glassStrength: 45,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    theme: "light",
    appearance: {
      backgroundColor: "#ffffff",
      cardColor: "rgba(0,0,0,0.03)",
      textColor: "#18181b",
      accentColor: "#18181b",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "outline",
      buttonRadius: 10,
      buttonWidth: "full",
      glassOpacity: 50,
      glassBlur: 25,
      glassStrength: 50,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    theme: "dark",
    appearance: {
      backgroundColor: "#0f172a",
      cardColor: "rgba(255,255,255,0.05)",
      textColor: "#e2e8f0",
      accentColor: "#38bdf8",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 25,
      glassBlur: 24,
      glassStrength: 55,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    theme: "dark",
    appearance: {
      backgroundColor: "#1a0b0e",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#fff1f2",
      accentColor: "#fb7185",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "glass",
      buttonRadius: 16,
      buttonWidth: "full",
      glassOpacity: 30,
      glassBlur: 28,
      glassStrength: 50,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "forest-green",
    name: "Forest Green",
    theme: "dark",
    appearance: {
      backgroundColor: "#052e16",
      cardColor: "rgba(255,255,255,0.05)",
      textColor: "#dcfce7",
      accentColor: "#86efac",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 28,
      glassBlur: 24,
      glassStrength: 52,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    theme: "dark",
    appearance: {
      backgroundColor: "#0f0518",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#fae8ff",
      accentColor: "#d946ef",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "solid",
      buttonRadius: 8,
      buttonWidth: "full",
      glassOpacity: 22,
      glassBlur: 20,
      glassStrength: 60,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "soft-peach",
    name: "Soft Peach",
    theme: "light",
    appearance: {
      backgroundColor: "#fff7ed",
      cardColor: "rgba(255,255,255,0.7)",
      textColor: "#431407",
      accentColor: "#f97316",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 14,
      buttonWidth: "full",
      glassOpacity: 55,
      glassBlur: 26,
      glassStrength: 48,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "royal-purple",
    name: "Royal Purple",
    theme: "dark",
    appearance: {
      backgroundColor: "#1e1b4b",
      cardColor: "rgba(255,255,255,0.05)",
      textColor: "#e0e7ff",
      accentColor: "#a5b4fc",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "glass",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 28,
      glassBlur: 26,
      glassStrength: 54,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    theme: "dark",
    appearance: {
      backgroundColor: "#082f49",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#e0f2fe",
      accentColor: "#7dd3fc",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 25,
      glassBlur: 28,
      glassStrength: 56,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    theme: "dark",
    appearance: {
      backgroundColor: "#2a0a0a",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#fef2f2",
      accentColor: "#fb923c",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "glass",
      buttonRadius: 14,
      buttonWidth: "full",
      glassOpacity: 30,
      glassBlur: 24,
      glassStrength: 52,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "berry",
    name: "Berry",
    theme: "dark",
    appearance: {
      backgroundColor: "#2e0b1c",
      cardColor: "rgba(255,255,255,0.05)",
      textColor: "#fce7f3",
      accentColor: "#f472b6",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 16,
      buttonWidth: "full",
      glassOpacity: 32,
      glassBlur: 26,
      glassStrength: 50,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "noir",
    name: "Noir",
    theme: "dark",
    appearance: {
      backgroundColor: "#000000",
      cardColor: "rgba(255,255,255,0.03)",
      textColor: "#ffffff",
      accentColor: "#ffffff",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "outline",
      buttonRadius: 0,
      buttonWidth: "full",
      glassOpacity: 20,
      glassBlur: 16,
      glassStrength: 40,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "pastel",
    name: "Pastel",
    theme: "light",
    appearance: {
      backgroundColor: "#fafaf9",
      cardColor: "rgba(255,255,255,0.8)",
      textColor: "#44403c",
      accentColor: "#a8a29e",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 18,
      buttonWidth: "full",
      glassOpacity: 60,
      glassBlur: 28,
      glassStrength: 45,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "slate",
    name: "Slate",
    theme: "light",
    appearance: {
      backgroundColor: "#f8fafc",
      cardColor: "rgba(255,255,255,0.7)",
      textColor: "#0f172a",
      accentColor: "#475569",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "outline",
      buttonRadius: 10,
      buttonWidth: "full",
      glassOpacity: 55,
      glassBlur: 24,
      glassStrength: 48,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "champagne",
    name: "Champagne",
    theme: "light",
    appearance: {
      backgroundColor: "#faf6ef",
      cardColor: "rgba(255,255,255,0.75)",
      textColor: "#3f3a30",
      accentColor: "#c9a86c",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "glass",
      buttonRadius: 14,
      buttonWidth: "full",
      glassOpacity: 50,
      glassBlur: 26,
      glassStrength: 50,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    theme: "light",
    appearance: {
      backgroundColor: "#ecfeff",
      cardColor: "rgba(255,255,255,0.8)",
      textColor: "#164e63",
      accentColor: "#06b6d4",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 12,
      buttonWidth: "full",
      glassOpacity: 58,
      glassBlur: 28,
      glassStrength: 46,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "coffee",
    name: "Coffee",
    theme: "dark",
    appearance: {
      backgroundColor: "#1c1917",
      cardColor: "rgba(255,255,255,0.04)",
      textColor: "#fafaf9",
      accentColor: "#d6d3d1",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "solid",
      buttonRadius: 10,
      buttonWidth: "full",
      glassOpacity: 32,
      glassBlur: 22,
      glassStrength: 48,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "lavender",
    name: "Lavender",
    theme: "light",
    appearance: {
      backgroundColor: "#f5f3ff",
      cardColor: "rgba(255,255,255,0.8)",
      textColor: "#4c1d95",
      accentColor: "#8b5cf6",
      fontFamily: "Inter",
      fontSize: 16,
      buttonStyle: "soft",
      buttonRadius: 14,
      buttonWidth: "full",
      glassOpacity: 55,
      glassBlur: 26,
      glassStrength: 48,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
  {
    id: "charcoal",
    name: "Charcoal",
    theme: "dark",
    appearance: {
      backgroundColor: "#171717",
      cardColor: "rgba(255,255,255,0.03)",
      textColor: "#e5e5e5",
      accentColor: "#737373",
      fontFamily: "Geist",
      fontSize: 16,
      buttonStyle: "outline",
      buttonRadius: 8,
      buttonWidth: "full",
      glassOpacity: 28,
      glassBlur: 20,
      glassStrength: 46,
      showAvatar: true,
      showBio: true,
      showSocial: true,
    },
  },
];
